//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EM_Report.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EM_Report.Domain.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Action_Active {
            get {
                return ResourceManager.GetString("Action_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string Action_AddNew {
            get {
                return ResourceManager.GetString("Action_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddOrRemoveFavorite.
        /// </summary>
        public static string Action_AddOrRemoveFavorite {
            get {
                return ResourceManager.GetString("Action_AddOrRemoveFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddRecentlyReport.
        /// </summary>
        public static string Action_AddRecentlyReport {
            get {
                return ResourceManager.GetString("Action_AddRecentlyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CanAccessReport.
        /// </summary>
        public static string Action_CanAccessReport {
            get {
                return ResourceManager.GetString("Action_CanAccessReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Action_Create {
            get {
                return ResourceManager.GetString("Action_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Action_Delete {
            get {
                return ResourceManager.GetString("Action_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all records in table.
        /// </summary>
        public static string Action_DeleteAll {
            get {
                return ResourceManager.GetString("Action_DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete By ID.
        /// </summary>
        public static string Action_DeleteByID {
            get {
                return ResourceManager.GetString("Action_DeleteByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Excel.
        /// </summary>
        public static string Action_ImportExcel {
            get {
                return ResourceManager.GetString("Action_ImportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InActive.
        /// </summary>
        public static string Action_InActive {
            get {
                return ResourceManager.GetString("Action_InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReArrange.
        /// </summary>
        public static string Action_ReArrange {
            get {
                return ResourceManager.GetString("Action_ReArrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Action_Save {
            get {
                return ResourceManager.GetString("Action_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Action_Update {
            get {
                return ResourceManager.GetString("Action_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateLevel.
        /// </summary>
        public static string Action_UpdateLevel {
            get {
                return ResourceManager.GetString("Action_UpdateLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateScheduleType.
        /// </summary>
        public static string Action_UpdateScheduleType {
            get {
                return ResourceManager.GetString("Action_UpdateScheduleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateStatus.
        /// </summary>
        public static string Action_UpdateStatus {
            get {
                return ResourceManager.GetString("Action_UpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        public static string btnAssign {
            get {
                return ResourceManager.GetString("btnAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string btnRemove {
            get {
                return ResourceManager.GetString("btnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Get_CreateSchedule {
            get {
                return ResourceManager.GetString("Get_CreateSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Dashboard by DashboardId.
        /// </summary>
        public static string Get_Dashboard_ByDashBoardID {
            get {
                return ResourceManager.GetString("Get_Dashboard_ByDashBoardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportId.
        /// </summary>
        public static string Get_Dashboard_ByReportId {
            get {
                return ResourceManager.GetString("Get_Dashboard_ByReportId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserID.
        /// </summary>
        public static string Get_Dashboard_ByUserId {
            get {
                return ResourceManager.GetString("Get_Dashboard_ByUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ByDashBoardId.
        /// </summary>
        public static string Get_DashBoardRegion_ByDashboardId {
            get {
                return ResourceManager.GetString("Get_DashBoardRegion_ByDashboardId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ByDashBoardRegionId.
        /// </summary>
        public static string Get_DashBoardRegion_ByDashboardRegionID {
            get {
                return ResourceManager.GetString("Get_DashBoardRegion_ByDashboardRegionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get_External_User_by_CronJob.
        /// </summary>
        public static string Get_External_User_by_CronJob {
            get {
                return ResourceManager.GetString("Get_External_User_by_CronJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get_Internal_User_by_CronJob.
        /// </summary>
        public static string Get_Internal_User_by_CronJob {
            get {
                return ResourceManager.GetString("Get_Internal_User_by_CronJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get_List_System.
        /// </summary>
        public static string Get_List_System {
            get {
                return ResourceManager.GetString("Get_List_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string Get_Option_List {
            get {
                return ResourceManager.GetString("Get_Option_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListByCategory.
        /// </summary>
        public static string Get_Option_List_ByCategory {
            get {
                return ResourceManager.GetString("Get_Option_List_ByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of External User Permission.
        /// </summary>
        public static string Get_Option_List_External_User_Permission {
            get {
                return ResourceManager.GetString("Get_Option_List_External_User_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite_Report.
        /// </summary>
        public static string Get_Option_List_Favourite {
            get {
                return ResourceManager.GetString("Get_Option_List_Favourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Internal User Permission.
        /// </summary>
        public static string Get_Option_List_Internal_User_Permission {
            get {
                return ResourceManager.GetString("Get_Option_List_Internal_User_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently_Report.
        /// </summary>
        public static string Get_Option_List_Recently {
            get {
                return ResourceManager.GetString("Get_Option_List_Recently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListRolesOfLevel.
        /// </summary>
        public static string Get_Option_List_RolesOfLevel {
            get {
                return ResourceManager.GetString("Get_Option_List_RolesOfLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get_Option_List_Traffic_Light.
        /// </summary>
        public static string Get_Option_List_Traffic_Light {
            get {
                return ResourceManager.GetString("Get_Option_List_Traffic_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List_Report_UserCanAccess.
        /// </summary>
        public static string Get_Option_List_UserCanAccess {
            get {
                return ResourceManager.GetString("Get_Option_List_UserCanAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string Get_Option_Single {
            get {
                return ResourceManager.GetString("Get_Option_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SingleDetail.
        /// </summary>
        public static string Get_Option_Single_Detail {
            get {
                return ResourceManager.GetString("Get_Option_Single_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External User Permission.
        /// </summary>
        public static string Get_Option_Single_External_User_Permission {
            get {
                return ResourceManager.GetString("Get_Option_Single_External_User_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal User Permission.
        /// </summary>
        public static string Get_Option_Single_Internal_User_Permission {
            get {
                return ResourceManager.GetString("Get_Option_Single_Internal_User_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PauseSchedule.
        /// </summary>
        public static string Get_PauseSchedule {
            get {
                return ResourceManager.GetString("Get_PauseSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get_Portfolio_Param_ClaimLiabilityIndicators.
        /// </summary>
        public static string Get_Portfolio_Param_ClaimLiabilityIndicators {
            get {
                return ResourceManager.GetString("Get_Portfolio_Param_ClaimLiabilityIndicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get_Portfolio_Param_ClaimOfficers.
        /// </summary>
        public static string Get_Portfolio_Param_ClaimOfficers {
            get {
                return ResourceManager.GetString("Get_Portfolio_Param_ClaimOfficers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get_Portfolio_Param_SubValues.
        /// </summary>
        public static string Get_Portfolio_Param_SubValues {
            get {
                return ResourceManager.GetString("Get_Portfolio_Param_SubValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get_Portfolio_Param_Values.
        /// </summary>
        public static string Get_Portfolio_Param_Values {
            get {
                return ResourceManager.GetString("Get_Portfolio_Param_Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResumeSchedule.
        /// </summary>
        public static string Get_ResumeSchedule {
            get {
                return ResourceManager.GetString("Get_ResumeSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SerializeSchedule.
        /// </summary>
        public static string Get_SerializeSchedule {
            get {
                return ResourceManager.GetString("Get_SerializeSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetSchedule.
        /// </summary>
        public static string Get_SetSchedule {
            get {
                return ResourceManager.GetString("Get_SetSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get_SystemRolePermission_By_SystemRoleId.
        /// </summary>
        public static string Get_SystemRolePermission_By_SystemRoleId {
            get {
                return ResourceManager.GetString("Get_SystemRolePermission_By_SystemRoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Get_Week {
            get {
                return ResourceManager.GetString("Get_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetField.
        /// </summary>
        public static string GetField {
            get {
                return ResourceManager.GetString("GetField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetFields.
        /// </summary>
        public static string GetFields {
            get {
                return ResourceManager.GetString("GetFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetInvisibleParameter.
        /// </summary>
        public static string GetInvisibleParameter {
            get {
                return ResourceManager.GetString("GetInvisibleParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetInvisibleParameterValue.
        /// </summary>
        public static string GetInvisibleParameterValue {
            get {
                return ResourceManager.GetString("GetInvisibleParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Max Reporting Date.
        /// </summary>
        public static string GetMaxRptDate {
            get {
                return ResourceManager.GetString("GetMaxRptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUser_By_UserNameOrEmail.
        /// </summary>
        public static string GetUser_By_UserNameOrEmail {
            get {
                return ResourceManager.GetString("GetUser_By_UserNameOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUserNameByEmail.
        /// </summary>
        public static string GetUserNameByEmail {
            get {
                return ResourceManager.GetString("GetUserNameByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetVisibleParametersInfo.
        /// </summary>
        public static string GetVisibleParametersInfo {
            get {
                return ResourceManager.GetString("GetVisibleParametersInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide bookmark.
        /// </summary>
        public static string Hide_Bookmark {
            get {
                return ResourceManager.GetString("Hide_Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsRig.
        /// </summary>
        public static string IsRig {
            get {
                return ResourceManager.GetString("IsRig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsTeamLeader.
        /// </summary>
        public static string IsTeamLeader {
            get {
                return ResourceManager.GetString("IsTeamLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the request page does not exist..
        /// </summary>
        public static string msg404 {
            get {
                return ResourceManager.GetString("msg404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while processing your request..
        /// </summary>
        public static string msg500 {
            get {
                return ResourceManager.GetString("msg500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to access this page or this feature..
        /// </summary>
        public static string msgAcessdenied {
            get {
                return ResourceManager.GetString("msgAcessdenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account was locked. Please contact Service Desk for assistance..
        /// </summary>
        public static string msgBlockedLogin {
            get {
                return ResourceManager.GetString("msgBlockedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when delete item.
        /// </summary>
        public static string msgDeleteError {
            get {
                return ResourceManager.GetString("msgDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one External Group.
        /// </summary>
        public static string msgExternalGroup_Require {
            get {
                return ResourceManager.GetString("msgExternalGroup_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2011 ASWIG. IT REPORT. All rights reserved..
        /// </summary>
        public static string msgFooter {
            get {
                return ResourceManager.GetString("msgFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported successfully!.
        /// </summary>
        public static string msgImportSuccess {
            get {
                return ResourceManager.GetString("msgImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect or the new password is similar with current password..
        /// </summary>
        public static string msgInvalidCurrentPassword {
            get {
                return ResourceManager.GetString("msgInvalidCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This domain account was locked or the username/password provided is incorrect. Please try again or contact Service Desk for assistance..
        /// </summary>
        public static string msgInvalidDomainAccount {
            get {
                return ResourceManager.GetString("msgInvalidDomainAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is incorrect..
        /// </summary>
        public static string msgInvalidEmail {
            get {
                return ResourceManager.GetString("msgInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid inputs. Please check your data again!.
        /// </summary>
        public static string msgInvalidInput {
            get {
                return ResourceManager.GetString("msgInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log into your email and click on the link.
        /// </summary>
        public static string msgInvalidResetPasswordRequest {
            get {
                return ResourceManager.GetString("msgInvalidResetPasswordRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification link is incorrect or expired..
        /// </summary>
        public static string msgInvalidUrlVerification {
            get {
                return ResourceManager.GetString("msgInvalidUrlVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or email is incorrect..
        /// </summary>
        public static string msgInvalidUserNameOrEmail {
            get {
                return ResourceManager.GetString("msgInvalidUserNameOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email or password provided is incorrect..
        /// </summary>
        public static string msgInvalidUserNameOrPassLogin {
            get {
                return ResourceManager.GetString("msgInvalidUserNameOrPassLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This level is already exist.
        /// </summary>
        public static string msgLevelDuplicate {
            get {
                return ResourceManager.GetString("msgLevelDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when load item.
        /// </summary>
        public static string msgLoadError {
            get {
                return ResourceManager.GetString("msgLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded successfully. Click on this box to close it.
        /// </summary>
        public static string msgLoadSuccess {
            get {
                return ResourceManager.GetString("msgLoadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one organisation of one system.
        /// </summary>
        public static string msgOrganisationRole_Require {
            get {
                return ResourceManager.GetString("msgOrganisationRole_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must process the importing data first..
        /// </summary>
        public static string msgProcessImportingData_Require {
            get {
                return ResourceManager.GetString("msgProcessImportingData_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved fail!.
        /// </summary>
        public static string msgSaveFail {
            get {
                return ResourceManager.GetString("msgSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully!.
        /// </summary>
        public static string msgSaveSuccess {
            get {
                return ResourceManager.GetString("msgSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending email failed. Please try again..
        /// </summary>
        public static string msgSendMailError {
            get {
                return ResourceManager.GetString("msgSendMailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent successfully..
        /// </summary>
        public static string msgSendMailSuccess {
            get {
                return ResourceManager.GetString("msgSendMailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when update item.
        /// </summary>
        public static string msgUpdateError {
            get {
                return ResourceManager.GetString("msgUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or email already exists..
        /// </summary>
        public static string msgUserDuplicate {
            get {
                return ResourceManager.GetString("msgUserDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /EMReporting/Reports/.
        /// </summary>
        public static string ReportPathPrefix {
            get {
                return ResourceManager.GetString("ReportPathPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request_Reset_Password.
        /// </summary>
        public static string Request_Reset_Password {
            get {
                return ResourceManager.GetString("Request_Reset_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset_Password.
        /// </summary>
        public static string Reset_Password {
            get {
                return ResourceManager.GetString("Reset_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show bookmark.
        /// </summary>
        public static string Show_Bookmark {
            get {
                return ResourceManager.GetString("Show_Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUS Eastern Standard Time.
        /// </summary>
        public static string strDestinationTimeZoneIdServer {
            get {
                return ResourceManager.GetString("strDestinationTimeZoneIdServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EndDate field for the schedule must occur after the StartDate field..
        /// </summary>
        public static string Sub_Validate_EndDate_After_StartDate {
            get {
                return ResourceManager.GetString("Sub_Validate_EndDate_After_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EndDate field is required..
        /// </summary>
        public static string Sub_Validate_StartDate {
            get {
                return ResourceManager.GetString("Sub_Validate_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add report to group: .
        /// </summary>
        public static string txtAddReportToGroup {
            get {
                return ResourceManager.GetString("txtAddReportToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign permission to report:.
        /// </summary>
        public static string txtAssignPermissionToReport {
            get {
                return ResourceManager.GetString("txtAssignPermissionToReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Trial List.
        /// </summary>
        public static string txtAuditActionList {
            get {
                return ResourceManager.GetString("txtAuditActionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Trial.
        /// </summary>
        public static string txtAuditHeader {
            get {
                return ResourceManager.GetString("txtAuditHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string txtCategoryAdd {
            get {
                return ResourceManager.GetString("txtCategoryAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Category.
        /// </summary>
        public static string txtCategoryEdit {
            get {
                return ResourceManager.GetString("txtCategoryEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category List.
        /// </summary>
        public static string txtCategoryList {
            get {
                return ResourceManager.GetString("txtCategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string txtCreatedOn {
            get {
                return ResourceManager.GetString("txtCreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string txtDescription {
            get {
                return ResourceManager.GetString("txtDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found !.
        /// </summary>
        public static string txtEmptyFilter {
            get {
                return ResourceManager.GetString("txtEmptyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value is invalid.
        /// </summary>
        public static string txtFilterValue {
            get {
                return ResourceManager.GetString("txtFilterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Management.
        /// </summary>
        public static string txtGroupHeader {
            get {
                return ResourceManager.GetString("txtGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        public static string txtItems {
            get {
                return ResourceManager.GetString("txtItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string txtName {
            get {
                return ResourceManager.GetString("txtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string txtOwner {
            get {
                return ResourceManager.GetString("txtOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Permission.
        /// </summary>
        public static string txtPermissionActionAdd {
            get {
                return ResourceManager.GetString("txtPermissionActionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Permission.
        /// </summary>
        public static string txtPermissionActionEdit {
            get {
                return ResourceManager.GetString("txtPermissionActionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission List.
        /// </summary>
        public static string txtPermissionActionList {
            get {
                return ResourceManager.GetString("txtPermissionActionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Management.
        /// </summary>
        public static string txtPermissionHeader {
            get {
                return ResourceManager.GetString("txtPermissionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string txtPermissionName {
            get {
                return ResourceManager.GetString("txtPermissionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Report.
        /// </summary>
        public static string txtReportActionAdd {
            get {
                return ResourceManager.GetString("txtReportActionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Report.
        /// </summary>
        public static string txtReportActionEdit {
            get {
                return ResourceManager.GetString("txtReportActionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report List.
        /// </summary>
        public static string txtReportActionList {
            get {
                return ResourceManager.GetString("txtReportActionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        public static string txtReportCategory {
            get {
                return ResourceManager.GetString("txtReportCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date:.
        /// </summary>
        public static string txtReportFromDate {
            get {
                return ResourceManager.GetString("txtReportFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group:.
        /// </summary>
        public static string txtReportGroup {
            get {
                return ResourceManager.GetString("txtReportGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Management.
        /// </summary>
        public static string txtReportHeader {
            get {
                return ResourceManager.GetString("txtReportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions:.
        /// </summary>
        public static string txtReportPermission {
            get {
                return ResourceManager.GetString("txtReportPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date:.
        /// </summary>
        public static string txtReportToDate {
            get {
                return ResourceManager.GetString("txtReportToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url:.
        /// </summary>
        public static string txtReportUrl {
            get {
                return ResourceManager.GetString("txtReportUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Details:.
        /// </summary>
        public static string txtReportView {
            get {
                return ResourceManager.GetString("txtReportView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string txtSearch {
            get {
                return ResourceManager.GetString("txtSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing {0} to {1} of {2} items.
        /// </summary>
        public static string txtShowItems {
            get {
                return ResourceManager.GetString("txtShowItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string txtStatus {
            get {
                return ResourceManager.GetString("txtStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column is duplicated, please change it..!!.
        /// </summary>
        public static string txtValidateDuplicationFilter {
            get {
                return ResourceManager.GetString("txtValidateDuplicationFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify_URL_Reset_Password.
        /// </summary>
        public static string Verify_URL_Reset_Password {
            get {
                return ResourceManager.GetString("Verify_URL_Reset_Password", resourceCulture);
            }
        }
    }
}
