#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EM_Report.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="hemprod")]
	public partial class EmicsModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public EmicsModelDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["hemprodConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EmicsModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmicsModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmicsModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmicsModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BROKER> BROKERs
		{
			get
			{
				return this.GetTable<BROKER>();
			}
		}
		
		public System.Data.Linq.Table<POLICY_TERM_DETAIL> POLICY_TERM_DETAILs
		{
			get
			{
				return this.GetTable<POLICY_TERM_DETAIL>();
			}
		}
		
		public System.Data.Linq.Table<PAYMENT_TYPE> PAYMENT_TYPEs
		{
			get
			{
				return this.GetTable<PAYMENT_TYPE>();
			}
		}
		
		public System.Data.Linq.Table<provider> providers
		{
			get
			{
				return this.GetTable<provider>();
			}
		}
		
		public System.Data.Linq.Table<Payment_Recovery> Payment_Recoveries
		{
			get
			{
				return this.GetTable<Payment_Recovery>();
			}
		}
		
		public System.Data.Linq.Table<person> persons
		{
			get
			{
				return this.GetTable<person>();
			}
		}
		
		public System.Data.Linq.Table<contact_extension> contact_extensions
		{
			get
			{
				return this.GetTable<contact_extension>();
			}
		}
		
		public System.Data.Linq.Table<Payment_Description> Payment_Descriptions
		{
			get
			{
				return this.GetTable<Payment_Description>();
			}
		}
		
		public System.Data.Linq.Table<CREDITOR> CREDITORs
		{
			get
			{
				return this.GetTable<CREDITOR>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.uvBROKER")]
	public partial class BROKER
	{
		
		private int _id;
		
		private string _BROKER_NO;
		
		private string _NAME;
		
		private bool _is_deleted;
		
		private string _Parent_Broker;
		
		public BROKER()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BROKER_NO", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string BROKER_NO
		{
			get
			{
				return this._BROKER_NO;
			}
			set
			{
				if ((this._BROKER_NO != value))
				{
					this._BROKER_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_deleted", DbType="Bit NOT NULL")]
		public bool is_deleted
		{
			get
			{
				return this._is_deleted;
			}
			set
			{
				if ((this._is_deleted != value))
				{
					this._is_deleted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parent_Broker", DbType="Char(8)")]
		public string Parent_Broker
		{
			get
			{
				return this._Parent_Broker;
			}
			set
			{
				if ((this._Parent_Broker != value))
				{
					this._Parent_Broker = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.uvPOLICY_TERM_DETAIL")]
	public partial class POLICY_TERM_DETAIL
	{
		
		private string _POLICY_NO;
		
		private string _LEGAL_NAME;
		
		private string _TRADING_NAME;
		
		private System.Nullable<int> _ACN_ARBN;
		
		private byte _POLICY_STATUS;
		
		private short _START_YEAR;
		
		private System.Nullable<double> _ABN;
		
		public POLICY_TERM_DETAIL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POLICY_NO", DbType="Char(19) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string POLICY_NO
		{
			get
			{
				return this._POLICY_NO;
			}
			set
			{
				if ((this._POLICY_NO != value))
				{
					this._POLICY_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LEGAL_NAME", DbType="VarChar(75)", UpdateCheck=UpdateCheck.Never)]
		public string LEGAL_NAME
		{
			get
			{
				return this._LEGAL_NAME;
			}
			set
			{
				if ((this._LEGAL_NAME != value))
				{
					this._LEGAL_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRADING_NAME", DbType="VarChar(75)", UpdateCheck=UpdateCheck.Never)]
		public string TRADING_NAME
		{
			get
			{
				return this._TRADING_NAME;
			}
			set
			{
				if ((this._TRADING_NAME != value))
				{
					this._TRADING_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACN_ARBN", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> ACN_ARBN
		{
			get
			{
				return this._ACN_ARBN;
			}
			set
			{
				if ((this._ACN_ARBN != value))
				{
					this._ACN_ARBN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POLICY_STATUS", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte POLICY_STATUS
		{
			get
			{
				return this._POLICY_STATUS;
			}
			set
			{
				if ((this._POLICY_STATUS != value))
				{
					this._POLICY_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_START_YEAR", DbType="SmallInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public short START_YEAR
		{
			get
			{
				return this._START_YEAR;
			}
			set
			{
				if ((this._START_YEAR != value))
				{
					this._START_YEAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABN", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> ABN
		{
			get
			{
				return this._ABN;
			}
			set
			{
				if ((this._ABN != value))
				{
					this._ABN = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.uvPAYMENT_TYPE")]
	public partial class PAYMENT_TYPE
	{
		
		private string _Payment_Type;
		
		private string _Payment_Group;
		
		private System.DateTime _Active_From_Date;
		
		private System.Nullable<System.DateTime> _Active_To_Date;
		
		public PAYMENT_TYPE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payment_Type", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Payment_Type
		{
			get
			{
				return this._Payment_Type;
			}
			set
			{
				if ((this._Payment_Type != value))
				{
					this._Payment_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payment_Group", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string Payment_Group
		{
			get
			{
				return this._Payment_Group;
			}
			set
			{
				if ((this._Payment_Group != value))
				{
					this._Payment_Group = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active_From_Date", DbType="SmallDateTime NOT NULL")]
		public System.DateTime Active_From_Date
		{
			get
			{
				return this._Active_From_Date;
			}
			set
			{
				if ((this._Active_From_Date != value))
				{
					this._Active_From_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active_To_Date", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Active_To_Date
		{
			get
			{
				return this._Active_To_Date;
			}
			set
			{
				if ((this._Active_To_Date != value))
				{
					this._Active_To_Date = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.uvPROVIDER")]
	public partial class provider
	{
		
		private int _ID;
		
		private string _wc_reg_no;
		
		private string _type;
		
		private string _firstname;
		
		private string _lastname;
		
		private string _organisation_name;
		
		private System.Nullable<bool> _is_deleted;
		
		public provider()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wc_reg_no", DbType="VarChar(8)")]
		public string wc_reg_no
		{
			get
			{
				return this._wc_reg_no;
			}
			set
			{
				if ((this._wc_reg_no != value))
				{
					this._wc_reg_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(1)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstname", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string firstname
		{
			get
			{
				return this._firstname;
			}
			set
			{
				if ((this._firstname != value))
				{
					this._firstname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastname", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string lastname
		{
			get
			{
				return this._lastname;
			}
			set
			{
				if ((this._lastname != value))
				{
					this._lastname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_organisation_name", DbType="VarChar(100)")]
		public string organisation_name
		{
			get
			{
				return this._organisation_name;
			}
			set
			{
				if ((this._organisation_name != value))
				{
					this._organisation_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_deleted", DbType="Bit")]
		public System.Nullable<bool> is_deleted
		{
			get
			{
				return this._is_deleted;
			}
			set
			{
				if ((this._is_deleted != value))
				{
					this._is_deleted = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.uvPAYMENT_RECOVERY")]
	public partial class Payment_Recovery
	{
		
		private int _ID;
		
		private string _Claim_No;
		
		private int _Payment_no;
		
		private System.DateTime _Transaction_date;
		
		private string _Estimate_type;
		
		private System.Nullable<int> _provider_id;
		
		private System.Nullable<char> _provider_type;
		
		private string _Payment_Type;
		
		private System.Nullable<int> _cid;
		
		private string _Service_Provider_Id;
		
		private System.Nullable<char> _Service_Provider_Type;
		
		private string _wc_service_provider_id;
		
		public Payment_Recovery()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Claim_No", DbType="Char(19) NOT NULL", CanBeNull=false)]
		public string Claim_No
		{
			get
			{
				return this._Claim_No;
			}
			set
			{
				if ((this._Claim_No != value))
				{
					this._Claim_No = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payment_no", DbType="Int NOT NULL")]
		public int Payment_no
		{
			get
			{
				return this._Payment_no;
			}
			set
			{
				if ((this._Payment_no != value))
				{
					this._Payment_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transaction_date", DbType="SmallDateTime NOT NULL")]
		public System.DateTime Transaction_date
		{
			get
			{
				return this._Transaction_date;
			}
			set
			{
				if ((this._Transaction_date != value))
				{
					this._Transaction_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estimate_type", DbType="Char(2)")]
		public string Estimate_type
		{
			get
			{
				return this._Estimate_type;
			}
			set
			{
				if ((this._Estimate_type != value))
				{
					this._Estimate_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provider_id", DbType="Int")]
		public System.Nullable<int> provider_id
		{
			get
			{
				return this._provider_id;
			}
			set
			{
				if ((this._provider_id != value))
				{
					this._provider_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provider_type", DbType="Char(1)")]
		public System.Nullable<char> provider_type
		{
			get
			{
				return this._provider_type;
			}
			set
			{
				if ((this._provider_type != value))
				{
					this._provider_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payment_Type", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Payment_Type
		{
			get
			{
				return this._Payment_Type;
			}
			set
			{
				if ((this._Payment_Type != value))
				{
					this._Payment_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cid", DbType="Int")]
		public System.Nullable<int> cid
		{
			get
			{
				return this._cid;
			}
			set
			{
				if ((this._cid != value))
				{
					this._cid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Service_Provider_Id", DbType="VarChar(20)")]
		public string Service_Provider_Id
		{
			get
			{
				return this._Service_Provider_Id;
			}
			set
			{
				if ((this._Service_Provider_Id != value))
				{
					this._Service_Provider_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Service_Provider_Type", DbType="Char(1)")]
		public System.Nullable<char> Service_Provider_Type
		{
			get
			{
				return this._Service_Provider_Type;
			}
			set
			{
				if ((this._Service_Provider_Type != value))
				{
					this._Service_Provider_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wc_service_provider_id", DbType="VarChar(20)")]
		public string wc_service_provider_id
		{
			get
			{
				return this._wc_service_provider_id;
			}
			set
			{
				if ((this._wc_service_provider_id != value))
				{
					this._wc_service_provider_id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.uvPERSON")]
	public partial class person
	{
		
		private int _ID;
		
		private string _FIRSTNAME;
		
		private string _LASTNAME;
		
		public person()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRSTNAME", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string FIRSTNAME
		{
			get
			{
				return this._FIRSTNAME;
			}
			set
			{
				if ((this._FIRSTNAME != value))
				{
					this._FIRSTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LASTNAME", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string LASTNAME
		{
			get
			{
				return this._LASTNAME;
			}
			set
			{
				if ((this._LASTNAME != value))
				{
					this._LASTNAME = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.uvCONTACT_EXTENSION")]
	public partial class contact_extension
	{
		
		private int _id;
		
		private System.Nullable<int> _person_id;
		
		private string _object_ref;
		
		private bool _is_primary;
		
		public contact_extension()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_person_id", DbType="Int")]
		public System.Nullable<int> person_id
		{
			get
			{
				return this._person_id;
			}
			set
			{
				if ((this._person_id != value))
				{
					this._person_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_object_ref", DbType="Char(19)")]
		public string object_ref
		{
			get
			{
				return this._object_ref;
			}
			set
			{
				if ((this._object_ref != value))
				{
					this._object_ref = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_primary", DbType="Bit NOT NULL")]
		public bool is_primary
		{
			get
			{
				return this._is_primary;
			}
			set
			{
				if ((this._is_primary != value))
				{
					this._is_primary = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.uvPAYMENT_DESCRIPTION")]
	public partial class Payment_Description
	{
		
		private int _Id;
		
		private string _Payment_Type;
		
		private System.Nullable<char> _Sub_Type;
		
		private string _Description;
		
		public Payment_Description()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payment_Type", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Payment_Type
		{
			get
			{
				return this._Payment_Type;
			}
			set
			{
				if ((this._Payment_Type != value))
				{
					this._Payment_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_Type", DbType="Char(1)")]
		public System.Nullable<char> Sub_Type
		{
			get
			{
				return this._Sub_Type;
			}
			set
			{
				if ((this._Sub_Type != value))
				{
					this._Sub_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(100)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.uvCREDITOR")]
	public partial class CREDITOR
	{
		
		private int _cid;
		
		private string _Creditor_no;
		
		private string _Name;
		
		private bool _is_deleted;
		
		private bool _Inactive;
		
		private System.Nullable<double> _ABN;
		
		private string _WC_Provider_Code;
		
		private string _Send_Chqs_To_Creditor;
		
		private string _AKA;
		
		private string _CN2Pay;
		
		private string _HC_Number;
		
		public CREDITOR()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cid", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int cid
		{
			get
			{
				return this._cid;
			}
			set
			{
				if ((this._cid != value))
				{
					this._cid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creditor_no", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string Creditor_no
		{
			get
			{
				return this._Creditor_no;
			}
			set
			{
				if ((this._Creditor_no != value))
				{
					this._Creditor_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_deleted", DbType="Bit NOT NULL")]
		public bool is_deleted
		{
			get
			{
				return this._is_deleted;
			}
			set
			{
				if ((this._is_deleted != value))
				{
					this._is_deleted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inactive", DbType="Bit NOT NULL")]
		public bool Inactive
		{
			get
			{
				return this._Inactive;
			}
			set
			{
				if ((this._Inactive != value))
				{
					this._Inactive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABN", DbType="Float")]
		public System.Nullable<double> ABN
		{
			get
			{
				return this._ABN;
			}
			set
			{
				if ((this._ABN != value))
				{
					this._ABN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WC_Provider_Code", DbType="VarChar(20)")]
		public string WC_Provider_Code
		{
			get
			{
				return this._WC_Provider_Code;
			}
			set
			{
				if ((this._WC_Provider_Code != value))
				{
					this._WC_Provider_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Send_Chqs_To_Creditor", DbType="Char(8)")]
		public string Send_Chqs_To_Creditor
		{
			get
			{
				return this._Send_Chqs_To_Creditor;
			}
			set
			{
				if ((this._Send_Chqs_To_Creditor != value))
				{
					this._Send_Chqs_To_Creditor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AKA", DbType="VarChar(255)")]
		public string AKA
		{
			get
			{
				return this._AKA;
			}
			set
			{
				if ((this._AKA != value))
				{
					this._AKA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CN2Pay", DbType="Char(8)")]
		public string CN2Pay
		{
			get
			{
				return this._CN2Pay;
			}
			set
			{
				if ((this._CN2Pay != value))
				{
					this._CN2Pay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HC_Number", DbType="Char(8)")]
		public string HC_Number
		{
			get
			{
				return this._HC_Number;
			}
			set
			{
				if ((this._HC_Number != value))
				{
					this._HC_Number = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
