<?xml version="1.0" encoding="utf-8"?><Database Name="EM_Reporting" Class="ReportModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ASWLAP04;Initial Catalog=EM_Reporting;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="EM_ReportingConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CONTROL" Member="CONTROLs">
    <Type Name="CONTROL">
      <Column Name="TYPE" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ITEM" Type="System.String" DbType="Char(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VALUE" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="TEXT_VALUE" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Users_Audit" Member="Users_Audits">
    <Type Name="Users_Audit">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Online_Locked_Until_Datetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Online_No_Of_Login_Attempts" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Last_Online_Login_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Is_System_User" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Action_Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Action_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Action_Owner" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.External_Groups" Member="External_Groups">
    <Type Name="External_Group">
      <Column Name="External_GroupId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Create_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Owner" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="External_Group_Report_External_Access" Member="Report_External_Accesses" ThisKey="External_GroupId" OtherKey="External_GroupId" Type="Report_External_Access" />
      <Association Name="External_Group_ReportUser" Member="ReportUsers" ThisKey="External_GroupId" OtherKey="External_GroupId" Type="ReportUser" />
    </Type>
  </Table>
  <Table Name="dbo.External_Groups_Audit" Member="External_Groups_Audits">
    <Type Name="External_Groups_Audit">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="External_GroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Action_Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Action_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Action_Owner" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Organisation_Levels" Member="Organisation_Levels">
    <Type Name="Organisation_Level">
      <Column Name="LevelId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Sort" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Create_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Owner" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="Organisation_Level_Organisation_Role" Member="Organisation_Roles" ThisKey="LevelId" OtherKey="LevelId" Type="Organisation_Role" />
      <Association Name="Organisation_Level_Report_Organisation_Level" Member="Report_Organisation_Levels" ThisKey="LevelId" OtherKey="LevelId" Type="Report_Organisation_Level" />
    </Type>
  </Table>
  <Table Name="dbo.Organisation_Roles" Member="Organisation_Roles">
    <Type Name="Organisation_Role">
      <Column Name="Organisation_RoleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Create_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Owner" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LevelId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Organisation_Role_ReportUser" Member="ReportUsers" ThisKey="Organisation_RoleId" OtherKey="Organisation_RoleId" Type="ReportUser" />
      <Association Name="Organisation_Level_Organisation_Role" Member="Organisation_Level" ThisKey="LevelId" OtherKey="LevelId" Type="Organisation_Level" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Organisation_Roles_Audit" Member="Organisation_Roles_Audits">
    <Type Name="Organisation_Roles_Audit">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Organisation_RoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Action_Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Action_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Action_Owner" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrganisationRole_Levels_Audit" Member="OrganisationRole_Levels_Audits">
    <Type Name="OrganisationRole_Levels_Audit">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LevelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Sort" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Action_Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Action_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Action_Owner" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Permissions" Member="Permissions">
    <Type Name="Permission">
      <Column Name="PermissionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="Permission_System_Role_Permission" Member="System_Role_Permissions" ThisKey="PermissionId" OtherKey="PermissionId" Type="System_Role_Permission" />
    </Type>
  </Table>
  <Table Name="dbo.RELEASE_VERSION" Member="RELEASE_VERSIONs">
    <Type Name="RELEASE_VERSION">
      <Column Name="Release_Version_No" Type="System.String" DbType="Char(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Object_Code" Type="System.String" DbType="Char(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Object_Version_No" Type="System.String" DbType="Char(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Owner" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Report_Categories" Member="Report_Categories">
    <Type Name="Report_Category">
      <Column Name="CategoryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Create_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Owner" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Report_Category_Report" Member="Reports" ThisKey="CategoryId" OtherKey="CategoryId" Type="Report" />
    </Type>
  </Table>
  <Table Name="dbo.Report_Categories_Audit" Member="Report_Categories_Audits">
    <Type Name="Report_Categories_Audit">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Action_Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Action_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Action_Owner" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Report_External_Access" Member="Report_External_Accesses">
    <Type Name="Report_External_Access">
      <Column Name="ReportId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="External_GroupId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Create_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Owner" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="External_Group_Report_External_Access" Member="External_Group" ThisKey="External_GroupId" OtherKey="External_GroupId" Type="External_Group" IsForeignKey="true" />
      <Association Name="Report_Report_External_Access" Member="Report" ThisKey="ReportId" OtherKey="ReportId" Type="Report" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Report_External_Access_Audit" Member="Report_External_Access_Audits">
    <Type Name="Report_External_Access_Audit">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReportId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="External_GroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Action_Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Action_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Action_Owner" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Report_Favorite" Member="Report_Favorites">
    <Type Name="Report_Favorite">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReportId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Create_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Report_Organisation_Levels" Member="Report_Organisation_Levels">
    <Type Name="Report_Organisation_Level">
      <Column Name="ReportId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LevelId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Create_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Owner" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Organisation_Level_Report_Organisation_Level" Member="Organisation_Level" ThisKey="LevelId" OtherKey="LevelId" Type="Organisation_Level" IsForeignKey="true" />
      <Association Name="Report_Report_Organisation_Level" Member="Report" ThisKey="ReportId" OtherKey="ReportId" Type="Report" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Report_Organisation_Roles_Audit" Member="Report_Organisation_Roles_Audits">
    <Type Name="Report_Organisation_Roles_Audit">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReportId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LevelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Action_Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Action_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Action_Owner" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Report_Recently" Member="Report_Recentlies">
    <Type Name="Report_Recently">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReportId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Create_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Reports" Member="Reports">
    <Type Name="Report">
      <Column Name="ReportId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ShortName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Create_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Owner" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Report_Report_External_Access" Member="Report_External_Accesses" ThisKey="ReportId" OtherKey="ReportId" Type="Report_External_Access" />
      <Association Name="Report_Report_Organisation_Level" Member="Report_Organisation_Levels" ThisKey="ReportId" OtherKey="ReportId" Type="Report_Organisation_Level" />
      <Association Name="Report_Subscription" Member="Subscriptions" ThisKey="ReportId" OtherKey="ReportId" Type="Subscription" />
      <Association Name="Report_Category_Report" Member="Report_Category" ThisKey="CategoryId" OtherKey="CategoryId" Type="Report_Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Reports_Audit" Member="Reports_Audits">
    <Type Name="Reports_Audit">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReportId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ShortName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Action_Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Action_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Action_Owner" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReportUsers" Member="ReportUsers">
    <Type Name="ReportUser">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Is_External_User" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TeamId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Organisation_RoleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="External_GroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="External_Group_ReportUser" Member="External_Group" ThisKey="External_GroupId" OtherKey="External_GroupId" Type="External_Group" IsForeignKey="true" />
      <Association Name="Organisation_Role_ReportUser" Member="Organisation_Role" ThisKey="Organisation_RoleId" OtherKey="Organisation_RoleId" Type="Organisation_Role" IsForeignKey="true" />
      <Association Name="Team_ReportUser" Member="Team" ThisKey="TeamId" OtherKey="TeamId" Type="Team" IsForeignKey="true" />
      <Association Name="User_ReportUser" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Status" Member="Status">
    <Type Name="Status">
      <Column Name="StatusId" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Subscriptions" Member="Subscriptions">
    <Type Name="Subscription">
      <Column Name="ReportId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubscriptionID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Owner" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ScheduleID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ScheduleType" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Report_Subscription" Member="Report" ThisKey="ReportId" OtherKey="ReportId" Type="Report" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Subscriptions_Audit" Member="Subscriptions_Audits">
    <Type Name="Subscriptions_Audit">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReportId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubscriptionID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Owner" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ScheduleID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Action_Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Action_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Action_Owner" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.System_Permissions" Member="System_Permissions">
    <Type Name="System_Permission">
      <Column Name="System_PermissionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="System_Permission_System_Role_Permission" Member="System_Role_Permissions" ThisKey="System_PermissionId" OtherKey="System_PermissionId" Type="System_Role_Permission" />
    </Type>
  </Table>
  <Table Name="dbo.System_Role_Permissions" Member="System_Role_Permissions">
    <Type Name="System_Role_Permission">
      <Column Name="System_RoleId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PermissionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="System_PermissionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Status" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Create_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Owner" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Permission_System_Role_Permission" Member="Permission" ThisKey="PermissionId" OtherKey="PermissionId" Type="Permission" IsForeignKey="true" />
      <Association Name="System_Permission_System_Role_Permission" Member="System_Permission" ThisKey="System_PermissionId" OtherKey="System_PermissionId" Type="System_Permission" IsForeignKey="true" />
      <Association Name="System_Role_System_Role_Permission" Member="System_Role" ThisKey="System_RoleId" OtherKey="System_RoleId" Type="System_Role" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.System_Role_Permissions_Audit" Member="System_Role_Permissions_Audits">
    <Type Name="System_Role_Permissions_Audit">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="System_RoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PermissionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="System_PermissionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Action_Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Action_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Action_Owner" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.System_Roles" Member="System_Roles">
    <Type Name="System_Role">
      <Column Name="System_RoleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="System_Role_System_Role_Permission" Member="System_Role_Permissions" ThisKey="System_RoleId" OtherKey="System_RoleId" Type="System_Role_Permission" />
      <Association Name="System_Role_SystemUser" Member="SystemUsers" ThisKey="System_RoleId" OtherKey="System_RoleId" Type="SystemUser" />
    </Type>
  </Table>
  <Table Name="dbo.SystemUsers" Member="SystemUsers">
    <Type Name="SystemUser">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="System_RoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="System_Role_SystemUser" Member="System_Role" ThisKey="System_RoleId" OtherKey="System_RoleId" Type="System_Role" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="User_SystemUser" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Teams" Member="Teams">
    <Type Name="Team">
      <Column Name="TeamId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Create_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Owner" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Team_ReportUser" Member="ReportUsers" ThisKey="TeamId" OtherKey="TeamId" Type="ReportUser" />
    </Type>
  </Table>
  <Table Name="dbo.Teams_Audit" Member="Teams_Audits">
    <Type Name="Teams_Audit">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TeamId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Action_Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Action_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Action_Owner" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Online_Locked_Until_Datetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Online_No_Of_Login_Attempts" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Last_Online_Login_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Create_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Owner" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Is_System_User" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="User_ReportUser" Member="ReportUser" ThisKey="UserId" OtherKey="UserId" Type="ReportUser" Cardinality="One" />
      <Association Name="User_SystemUser" Member="SystemUser" ThisKey="UserId" OtherKey="UserId" Type="SystemUser" Cardinality="One" />
      <Association Name="User_AddressBook" Member="AddressBooks" ThisKey="UserId" OtherKey="UserId" Type="AddressBook" />
    </Type>
  </Table>
  <Table Name="dbo.AddressBook" Member="AddressBooks">
    <Type Name="AddressBook">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="BusinessPhone" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="HomePhone" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MobilePhone" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="User_AddressBook" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>