//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EM_Report.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DartEntities : DbContext
    {
        public DartEntities()
            : base("name=DartEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dashboard_FavourDO> Dashboard_FavourDO { get; set; }
        public virtual DbSet<Dashboard_Graph_DescriptionDO> Dashboard_Graph_DescriptionDO { get; set; }
        public virtual DbSet<Dashboard_LevelDO> Dashboard_LevelDO { get; set; }
        public virtual DbSet<Dashboard_OrganisationRole_LevelDO> Dashboard_OrganisationRole_LevelDO { get; set; }
        public virtual DbSet<Dashboard_TimeAccessDO> Dashboard_TimeAccessDO { get; set; }
        public virtual DbSet<Dashboard_Traffic_Light_RuleDO> Dashboard_Traffic_Light_RuleDO { get; set; }
        public virtual DbSet<DashboardDO> DashboardDOes { get; set; }
        public virtual DbSet<EML_AWC_ProjectionDO> EML_AWC_ProjectionDO { get; set; }
        public virtual DbSet<EML_PortfolioDO> EML_PortfolioDO { get; set; }
        public virtual DbSet<EML_RTW_Target_BaseDO> EML_RTW_Target_BaseDO { get; set; }
        public virtual DbSet<External_GroupDO> External_GroupDO { get; set; }
        public virtual DbSet<HEM_AWC_ProjectionDO> HEM_AWC_ProjectionDO { get; set; }
        public virtual DbSet<HEM_PortfolioDO> HEM_PortfolioDO { get; set; }
        public virtual DbSet<HEM_RTW_Target_BaseDO> HEM_RTW_Target_BaseDO { get; set; }
        public virtual DbSet<Organisation_LevelDO> Organisation_LevelDO { get; set; }
        public virtual DbSet<Organisation_RoleDO> Organisation_RoleDO { get; set; }
        public virtual DbSet<PermissionDO> PermissionDOes { get; set; }
        public virtual DbSet<Report_CategoryDO> Report_CategoryDO { get; set; }
        public virtual DbSet<Report_External_AccessDO> Report_External_AccessDO { get; set; }
        public virtual DbSet<Report_FavoriteDO> Report_FavoriteDO { get; set; }
        public virtual DbSet<Report_Organisation_LevelDO> Report_Organisation_LevelDO { get; set; }
        public virtual DbSet<ReportDO> ReportDOes { get; set; }
        public virtual DbSet<ReportUserDO> ReportUserDOes { get; set; }
        public virtual DbSet<StatusDO> StatusDOes { get; set; }
        public virtual DbSet<System_PermissionDO> System_PermissionDO { get; set; }
        public virtual DbSet<System_Role_PermissionDO> System_Role_PermissionDO { get; set; }
        public virtual DbSet<System_RoleDO> System_RoleDO { get; set; }
        public virtual DbSet<SystemDO> SystemDOes { get; set; }
        public virtual DbSet<TeamDO> TeamDOes { get; set; }
        public virtual DbSet<TMF_AWC_ProjectionDO> TMF_AWC_ProjectionDO { get; set; }
        public virtual DbSet<TMF_PortfolioDO> TMF_PortfolioDO { get; set; }
        public virtual DbSet<TMF_RTW_Target_BaseDO> TMF_RTW_Target_BaseDO { get; set; }
        public virtual DbSet<UserDO> UserDOes { get; set; }
        public virtual DbSet<Report_RecentlyDO> Report_RecentlyDO1 { get; set; }
        public virtual DbSet<TMF_Agencies_Sub_CategoryDO> TMF_Agencies_Sub_CategoryDO { get; set; }
        public virtual DbSet<SystemUserDO> SystemUserDOes { get; set; }
        public virtual DbSet<CONTROLDO> CONTROLDOes { get; set; }
        public virtual DbSet<DashboardExternal_GroupsDO> DashboardExternal_GroupsDO { get; set; }
        public virtual DbSet<WOW_PortfolioDO> WOW_PortfolioDO { get; set; }
        public virtual DbSet<Dashboard_Claim_Liability_IndicatorDO> Dashboard_Claim_Liability_IndicatorDO { get; set; }
    
        public virtual ObjectResult<Nullable<int>> PRO_Login(string email, string passWord, Nullable<int> noLimitLoginAttempts, Nullable<int> noDaysBlockedAttempts, Nullable<int> systemId)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passWordParameter = passWord != null ?
                new ObjectParameter("PassWord", passWord) :
                new ObjectParameter("PassWord", typeof(string));
    
            var noLimitLoginAttemptsParameter = noLimitLoginAttempts.HasValue ?
                new ObjectParameter("NoLimitLoginAttempts", noLimitLoginAttempts) :
                new ObjectParameter("NoLimitLoginAttempts", typeof(int));
    
            var noDaysBlockedAttemptsParameter = noDaysBlockedAttempts.HasValue ?
                new ObjectParameter("NoDaysBlockedAttempts", noDaysBlockedAttempts) :
                new ObjectParameter("NoDaysBlockedAttempts", typeof(int));
    
            var systemIdParameter = systemId.HasValue ?
                new ObjectParameter("SystemId", systemId) :
                new ObjectParameter("SystemId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PRO_Login", emailParameter, passWordParameter, noLimitLoginAttemptsParameter, noDaysBlockedAttemptsParameter, systemIdParameter);
        }
    }
}
