//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EM_Report.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dashboard_TimeAccessDO
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public int UserId { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<int> Owner { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
