//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EM_Report.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dashboard_OrganisationRole_LevelDO
    {
        public int DashboardOrganisationlevelId { get; set; }
        public int DashboardId { get; set; }
        public int DashboardLevelId { get; set; }
        public int LevelId { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<int> Owner { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual Dashboard_LevelDO Dashboard_Levels { get; set; }
        public virtual DashboardDO Dashboard { get; set; }
        public virtual Organisation_LevelDO Organisation_Levels { get; set; }
    }
}
