//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EM_Report.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dashboard_LevelDO
    {
        public Dashboard_LevelDO()
        {
            this.Dashboard_OrganisationRole_Levels = new HashSet<Dashboard_OrganisationRole_LevelDO>();
        }
    
        public int DashboardLevelId { get; set; }
        public string Name { get; set; }
        public short Sort { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<int> Owner { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<short> Status { get; set; }
    
        public virtual ICollection<Dashboard_OrganisationRole_LevelDO> Dashboard_OrganisationRole_Levels { get; set; }
    }
}
