//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EM_Report.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HEM_AWC_ProjectionDO
    {
        public int Id { get; set; }
        public string Unit_Type { get; set; }
        public string Unit_Name { get; set; }
        public string Type { get; set; }
        public System.DateTime Time_Id { get; set; }
        public double Projection { get; set; }
    }
}
