//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EM_Report.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMF_Agencies_Sub_CategoryDO
    {
        public int Id { get; set; }
        public string AgencyId { get; set; }
        public string AgencyName { get; set; }
        public string Sub_Category { get; set; }
        public string POLICY_NO { get; set; }
        public string Group { get; set; }
    }
}
