//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EM_Report.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EM_Report.BLL.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        public static string btnAssign {
            get {
                return ResourceManager.GetString("btnAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string btnRemove {
            get {
                return ResourceManager.GetString("btnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg {
            get {
                return ResourceManager.GetString("msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the request page not exist in system..
        /// </summary>
        public static string msg404 {
            get {
                return ResourceManager.GetString("msg404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while processing your request..
        /// </summary>
        public static string msg500 {
            get {
                return ResourceManager.GetString("msg500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to access this page or this feature..
        /// </summary>
        public static string msgAcessdenied {
            get {
                return ResourceManager.GetString("msgAcessdenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account was blocked..
        /// </summary>
        public static string msgBlockedLogin {
            get {
                return ResourceManager.GetString("msgBlockedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when delete item.
        /// </summary>
        public static string msgDeleteError {
            get {
                return ResourceManager.GetString("msgDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2011 ASWIG.IT REPORT. All rights reserved..
        /// </summary>
        public static string msgFooter {
            get {
                return ResourceManager.GetString("msgFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect or the new password is invalid..
        /// </summary>
        public static string msgInvalidCurrentPassword {
            get {
                return ResourceManager.GetString("msgInvalidCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid inputs. Please check your data again!.
        /// </summary>
        public static string msgInvalidInput {
            get {
                return ResourceManager.GetString("msgInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or email is incorrect..
        /// </summary>
        public static string msgInvalidUserNameOrEmail {
            get {
                return ResourceManager.GetString("msgInvalidUserNameOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string msgInvalidUserNameOrPassLogin {
            get {
                return ResourceManager.GetString("msgInvalidUserNameOrPassLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when load item.
        /// </summary>
        public static string msgLoadError {
            get {
                return ResourceManager.GetString("msgLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded successfully. Click on this box to close it.
        /// </summary>
        public static string msgLoadSuccess {
            get {
                return ResourceManager.GetString("msgLoadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved fail!.
        /// </summary>
        public static string msgSaveFail {
            get {
                return ResourceManager.GetString("msgSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully!.
        /// </summary>
        public static string msgSaveSuccess {
            get {
                return ResourceManager.GetString("msgSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed sent email. Please try again..
        /// </summary>
        public static string msgSendMailError {
            get {
                return ResourceManager.GetString("msgSendMailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent successfully..
        /// </summary>
        public static string msgSendMailSuccess {
            get {
                return ResourceManager.GetString("msgSendMailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when update item.
        /// </summary>
        public static string msgUpdateError {
            get {
                return ResourceManager.GetString("msgUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or email already exist in database..
        /// </summary>
        public static string msgUserDuplicate {
            get {
                return ResourceManager.GetString("msgUserDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUS Eastern Standard Time.
        /// </summary>
        public static string strDestinationTimeZoneIdServer {
            get {
                return ResourceManager.GetString("strDestinationTimeZoneIdServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add report to group: .
        /// </summary>
        public static string txtAddReportToGroup {
            get {
                return ResourceManager.GetString("txtAddReportToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign permission to report:.
        /// </summary>
        public static string txtAssignPermissionToReport {
            get {
                return ResourceManager.GetString("txtAssignPermissionToReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Trial List.
        /// </summary>
        public static string txtAuditActionList {
            get {
                return ResourceManager.GetString("txtAuditActionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Trial.
        /// </summary>
        public static string txtAuditHeader {
            get {
                return ResourceManager.GetString("txtAuditHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string txtCategoryAdd {
            get {
                return ResourceManager.GetString("txtCategoryAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Category.
        /// </summary>
        public static string txtCategoryEdit {
            get {
                return ResourceManager.GetString("txtCategoryEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category List.
        /// </summary>
        public static string txtCategoryList {
            get {
                return ResourceManager.GetString("txtCategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string txtCreatedOn {
            get {
                return ResourceManager.GetString("txtCreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string txtDescription {
            get {
                return ResourceManager.GetString("txtDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Management.
        /// </summary>
        public static string txtGroupHeader {
            get {
                return ResourceManager.GetString("txtGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        public static string txtItems {
            get {
                return ResourceManager.GetString("txtItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string txtName {
            get {
                return ResourceManager.GetString("txtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string txtOwner {
            get {
                return ResourceManager.GetString("txtOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Permission.
        /// </summary>
        public static string txtPermissionActionAdd {
            get {
                return ResourceManager.GetString("txtPermissionActionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Permission.
        /// </summary>
        public static string txtPermissionActionEdit {
            get {
                return ResourceManager.GetString("txtPermissionActionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission List.
        /// </summary>
        public static string txtPermissionActionList {
            get {
                return ResourceManager.GetString("txtPermissionActionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Management.
        /// </summary>
        public static string txtPermissionHeader {
            get {
                return ResourceManager.GetString("txtPermissionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string txtPermissionName {
            get {
                return ResourceManager.GetString("txtPermissionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Report.
        /// </summary>
        public static string txtReportActionAdd {
            get {
                return ResourceManager.GetString("txtReportActionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Report.
        /// </summary>
        public static string txtReportActionEdit {
            get {
                return ResourceManager.GetString("txtReportActionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report List.
        /// </summary>
        public static string txtReportActionList {
            get {
                return ResourceManager.GetString("txtReportActionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        public static string txtReportCategory {
            get {
                return ResourceManager.GetString("txtReportCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date:.
        /// </summary>
        public static string txtReportFromDate {
            get {
                return ResourceManager.GetString("txtReportFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group:.
        /// </summary>
        public static string txtReportGroup {
            get {
                return ResourceManager.GetString("txtReportGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Management.
        /// </summary>
        public static string txtReportHeader {
            get {
                return ResourceManager.GetString("txtReportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions:.
        /// </summary>
        public static string txtReportPermission {
            get {
                return ResourceManager.GetString("txtReportPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date:.
        /// </summary>
        public static string txtReportToDate {
            get {
                return ResourceManager.GetString("txtReportToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url:.
        /// </summary>
        public static string txtReportUrl {
            get {
                return ResourceManager.GetString("txtReportUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Details:.
        /// </summary>
        public static string txtReportView {
            get {
                return ResourceManager.GetString("txtReportView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string txtSearch {
            get {
                return ResourceManager.GetString("txtSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing {0} to {1} of {2} items.
        /// </summary>
        public static string txtShowItems {
            get {
                return ResourceManager.GetString("txtShowItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string txtStatus {
            get {
                return ResourceManager.GetString("txtStatus", resourceCulture);
            }
        }
    }
}
