SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
-- =============================================
-- Author:		<Author,,Name>
-- CREATE date: <CREATE Date,,>
-- Description:	<Description,,>
-- =============================================
IF EXISTS(SELECT * FROM sys.views WHERE name = 'vw_WOW_Claim_Detail')
	DROP VIEW [dbo].[vw_WOW_Claim_Detail]
GO
	CREATE VIEW [dbo].[vw_WOW_Claim_Detail]
	AS
		SELECT	A.JURISDICTIONCODE AS JURISDICTION,
				A.CLAIMID AS CLAIMID,
				A.CLAIM AS CLAIM_NO,
                (CASE WHEN A.CLAIMSTATUS = 'C' THEN 'Y' ELSE 'N' END) AS CLAIM_CLOSED_FLAG,
                A.CLAIMSTATUS,
                H.REOPENREASON As REOPEN_REASON,
                R.LIABILITYSTATUSCODE AS CLAIM_LIABILITY_INDICATOR, 
                R.WORKSTATUSCODE AS WORK_STATUS_CODE, 
				A.CASEMANAGERID AS CLAIMS_OFFICER,
				W.ESTIMPAIRMENT AS WPI,
				R.InjuryResult AS INJURYRESULT,
                R.SERIOUSLYINJUREDCODE AS SERIOUS_INJURY_CODE,
                W.ACTUALIMPAIRMENT AS WPI_FINAL,
                A.dateopened AS DTE_CLAIM_ENTERED, 
                A.DateClosed AS DTE_CLAIM_CLOSED,
                A.DateReopened AS DTE_CLAIM_REOPENED, 
                A.DateReceived AS DTE_CLAIM_RECEIVED,
                C.OFFICER, 
                A.JURISDICTIONCODE AS [GROUP], 
                C.GRP AS TEAM, 
                A.CLAIM AS ID, 
/*              ACCIDENT_LOCATION_CODE, ACCIDENT_LOCATION_DESC, ACCIDENT_ADDRESS, */
/*              ACCIDENT_LOCATION_LOCALITY,   ACCIDENT_LOCATION_POSTCODE, ACCIDENT_REPORTED_TO,*/
/*              AGENCY_OF_ACCIDENT,  ALTERNATE_ADDRESS, ALTERNATE_LOCALITY,      ALTERNATE_STATE, */
/*              ALTERNATE_POSTCODE, ASIC, ANZSIC, CHECKED_BY, */ 
                A.CC AS COST_CENTRE,    
                M.BIRTHCOUNTRYCODE AS COUNTRY_OF_BIRTH, 
/*              DEPENDANTS_CHILDREN,    DEPENDANTS_OTHER, DIRECT_EMPLOYEE,  */
                R.DUTYSTATUS AS DUTY_STATUS_CODE,   
                R.FULLPARTTIMECODE AS FULL_PART_IND, 
                2 as FUND, A.FIRSTNAMES AS GIVEN_NAMES, 
                (CASE WHEN A.ISMALE = 1 THEN 'M' ELSE 'F' END) AS GENDER_CODE,
/*              IMA,  IMP_ACT_COMPLETE, */
                A.INJURYDETAILS AS INJURY_COMMENT, 
/*              INTERPRETER_IND, IS_MEDICAL_ONLY,   IS_SENT2WC, IS_REHAB_ADDED,      IS_REHAB,*/
/*              IS_TIME_LOST, IS_WCL_ADDED,   IS_NULL, IS_EXCESS_APPLIES,   IS_NO_POLICY_CHECK,     IS_IMP_REVIEWS_ADDED,*/
/*              IS_CONVERTED, IS_NO_SI_WARNING,     IS_READ_ONLY, IS_PLAN_NOT_REQUIRED,      */
/*              IS_IMA_CONTACT_START, IS_IMA_ASS_MSG_SENT,*/
/*              IS_SCREENED, IS_CTP_RECOVERY, IS_GST_REGISTERED, IS_RESTRICTED, IS_GST_REG_CHANGED, */
                M.LANGUAGECODE AS LANGUAGE_CODE, 
                A.SURNAME AS LAST_NAMES,
/*              LOCALITY,*/
                A.INJURYSITE AS LOCATION_OF_INJURY, 
                R.MAINTASKS AS MAIN_TASKS,
                /*MARRIED_IND, */
                R.MECHANISMID AS MECHANISM_OF_INJURY,    
                A.INJURYCODE AS NATURE_OF_INJURY,
/*              NOM_TREATING_DOCTOR, NOM_TREATING_SPECIALIST, */
                A.OCCUPATION AS OCCUPATION_CODE, 
                /* OWNER,      PERMANENT_IND,*/
                R.POLICYNO AS POLICY_NO,/*    POSTAL_FROM_POLICY,     */
                A.POSTCODE As POSTCODE, 
                A.HOMEPHONE AS PHONE_NO,      /*    PHONE_NO1, */
                A.INSYEAR AS POLICY_YEAR, 
/*              REHAB_COORDINATOR, REHAB_COORDINATOR_PHONE, REHAB_COORDINATOR_PHONE1,*/
/*              RENEWAL_NO, RESULT_OF_INJURY_CODE, REVIEWS_ADDED, SOURCE, SHARED_CLAIM_CODE,  STATE, STREET_ADDRESS, */
                A.NAMEPREFIX AS SUFFIX,
                J.WICRATENUMBER As TARIFF_NO,
                /*TRAINING_STATUS_CODE,  */
                E.ORDINARYEARNINGS AS WEEKLY_WAGE,  
                E.ORDINARYHOURSPERWEEK AS WORK_HOURS, 
                E.DAYSWORKEDPERWEEK AS WORK_DAYS,
/*              WORKPLACE_STREET_ADDRESS, WORKPLACE_LOCALITY, WORKPLACE_POSTCODE, WORKPLACE_SIZE, */ 
				A.WORKPHONE AS WORKPLACE_PHONE,
/*              WORKPLACE_FAX, WORKPLACE_EMAIL, DIRECT_EMPLOYEE_COMMENT, PAY_SUSPEND_REASON, PAY_SUSPEND_CODE, NATURE_ID,*/
/*              NOM_REHAB_PROVIDER, ASCO_ID, ITC_PCENT,WEEKLY_WAGE_CURRENT,PILOT_FLAGS,WORK_STATUS_CODE_CHECKS,*/
/*              PROCESS_FLAGS,  NOTIFIED_BY, TNODE, BRANCH_NO, INJURY_COMMENT_HOW, NOTIFIER_ID, ASCO_VERSION, TOOCS_VERSION,*/
/*              AGENCY_OF_INJURY, WORKER_ADDRESS_ID, ALTERNATE_ADDRESS_ID, WORKPLACE_ADDRESS_ID, ACCIDENT_ADDRESS_ID,*/
                A.EMPLOYEENO AS EMPLOYEE_NO,
/*              EMPLOYER_INCIDENT_NO,  A.WORKPHONE AS PHONE_WORK, */
                A.CC AS COST_CODE,
                M.TERMINATIONREASON AS EMPLOYMENT_TERMINATED_REASON,
/*              LANGUAGE_VERSION, ASIC_VERSION, ANZSIC_VERSION,*/
                E.OVERTIMEALLOWANCE AS OT_ALLOWANCES,
                E.NONPECUNIARY AS NON_PECUNIARY,
/*              TOTAL_BENEFIT_WEEKS, HOURS_PRE_INJURY,EARNINGS_PRE_INJURY, CHECKED_DTE,COMMENCEMENT_DTE,*/
                A.DOB AS DTE_OF_BIRTH,
/*              DTE_CREATED, TIME_CREATED, DTE_CLAIMFORM_RECEIVED, */
                A.InjuryDate AS DTE_OF_INJURY, 
                R.DateReceivedByEmployer AS DTE_NOTICE_GIVEN,
/*				R.TIME_RECEIVEDBYEMPLOYER AS TIME_NOTICE_GIVEN, */
                M.StartDate AS DTE_EMPLOYED, 
                M.DATEDECEASED AS DTE_DECEASED,       
                M.TERMINATIONDATE AS TERMINATED_DTE,
/*              LAST_SECURE_DTE,*/
                R.SIGNIFICANTINJURYDATE AS DTE_SIGNIFICANT,/*,DTE_CONTACT_INITIATED,TIME_CONTACT_INITIATED,*/ 
				(CASE WHEN A.ISMALE = 1 THEN DATEADD(MONTH, 12, A.DOB)
                ELSE DATEADD(MONTH, 12, A.DOB) END) AS RETIREMENT_DTE,             
                /*(CASE WHEN A.ISMALE = 1 THEN Intnx('Month',A.DOB,INPUT(PUT(A.DOB,RET_MALE.),5.1)*12,'Sameday')
                ELSE Intnx('Month',A.DOB,INPUT(PUT(A.DOB,RET_FEMALE.),5.1)*12,'Sameday') END) AS RETIREMENT_DTE ,*/
                R.MEDICALBENEFITSCEASES AS MEDICAL_BENEFIT_CEASED_DTE,
                /*ENTITLEMENT_ASOFDTE, BROKER_NO, */
                2 AS CELL_NO

		FROM ACCDATA AS A
				LEFT JOIN WORKCOVEREARNINGS               AS E ON A.CLAIMID  = E.CLAIMID
				LEFT JOIN CLAIMMONTHLYHISTORY             AS H ON A.CLAIMID  = H.CLAIMID
				LEFT JOIN ClientJurisdictional            AS J ON A.CLIENTID = J.CLIENTID AND A.JURISDICTIONCODE = J.JURISDICTIONCODE
				LEFT JOIN MEMBER                          AS M ON A.MEMBERID = M.MEMBERID
				LEFT JOIN ACCREGULATOR                    AS R ON A.CLAIMID  = R.CLAIMID
				LEFT JOIN Vw_workcover_totalimpairment    AS W ON A.CLAIMID  = W.CLAIMID
				LEFT JOIN vw_WOW_Claims_Officers          AS C ON A.CASEMANAGERID = C.OFFICER_ID
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO