/****** Object:  StoredProcedure [dbo].[usp_Generate_WOW_User]    Script Date: 20/05/2014 14:31:45 ******/
SET ANSI_NULLS OFF
GO

SET QUOTED_IDENTIFIER OFF
GO
-- =============================================
-- Author:		<Author,,Name>
-- CREATE date: <CREATE Date,,>
-- Description:	<Description,,>
-- =============================================
IF EXISTS (SELECT * FROM dbo.sysobjects where id = object_id(N'[dbo].[usp_Generate_WOW_User]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
	DROP PROCEDURE [dbo].[usp_Generate_WOW_User]
GO

CREATE PROCEDURE [dbo].[usp_Generate_WOW_User]
	@wow_datebase_name varchar(20)
AS
BEGIN
	IF OBJECT_ID('tempdb..#wow_temp') IS NOT NULL DROP TABLE #wow_temp
	
	--VARIABLES FOR EXTERNAL GROUP--
	DECLARE @WOW_Internal_Group_Id int
	DECLARE @WOW_External_Group_Id int
	
	--ADD WOW TO SYSTEM TABLE--
	INSERT INTO [Dart].[dbo].[Systems] ([Name], [Description], [Owner], [Status])
	SELECT 'WOW', 'System for WOW', 1, 1
	WHERE not exists (SELECT * FROM [Dart].[dbo].[Systems] WHERE Name like '%WOW%')

	
	--ADD WOW TO DASHBOARD TABLE--
	INSERT INTO [Dart].[dbo].[Dashboards] (SystemId, Name, Url, Create_Date, [Status])
	SELECT (SELECT SystemId FROM [Dart].[dbo].[Systems] WHERE Name = 'WOW')
			, 'WOW CPR'
			, 'Level0,WOW_Level1,WOW_CPR_Week_Month_Summary,CPR_Summary,CPR_Summary,CPR_Summary,CPR_Summary,CPR_Summary' 
			, GETDATE()
			,1
	WHERE not exists (SELECT * FROM [Dart].[dbo].[Dashboards] WHERE Name like '%WOW%')
	
	--ADD WOW External TO EXTERNAL GROUP--
	INSERT INTO [Dart].[dbo].[External_Groups] (Name, [Status], Create_Date, SystemId)
	SELECT 'WOW External', 1, GETDATE(), (SELECT SystemId FROM [Dart].[dbo].[Systems] WHERE Name = 'WOW')
	WHERE not exists (SELECT * FROM [Dart].[dbo].[External_Groups] WHERE Name like '%WOW External%')
	
	--ADD WOW Internal TO EXTERNAL GROUP--
	INSERT INTO [Dart].[dbo].[External_Groups] (Name, [Status], Create_Date, SystemId)
	SELECT 'WOW Internal', 1, GETDATE(), (SELECT SystemId FROM [Dart].[dbo].[Systems] WHERE Name = 'WOW')
	WHERE not exists (SELECT * FROM [Dart].[dbo].[External_Groups] WHERE Name like '%WOW Internal%')
	
	
	--ADD USER FROM Permissn TO USER TABLE--
	--build dynamic query--
	DECLARE @SQL varchar (MAX)		
	SET @SQL = 'SELECT ''WOW\'' + Username as UserName
					,isnull(Password,'''') as [Password]
					,SUBSTRING(FullName,0,CHARINDEX('' '',fullname)) as FirstName
					,SUBSTRING(FullName,CHARINDEX('' '',fullname) + 1,LEN(fullname)) as LastName
					,EmailAddress as Email
					,case when ActiveUser = ''y'' then 1 else 0 end as Status
					,MobilePhone as Phone
					,GETDATE() as Create_Date
					,0 as Is_System_User
					,(select SystemId from [Dart].[dbo].[Systems] where Name like ''%WOW%'') as Default_System_Id
				FROM [' + @wow_datebase_name + '].[dbo].[Permissn]
				WHERE (EmailAddress like ''%@aswigsolutions.com%''
					   OR EmailAddress like ''%@employersmutual.com.au%''
					   OR EmailAddress like ''%@woolworths.com.au%'')
					   AND EmailAddress is not null
					   AND UserName not like ''%_stars''
					   AND CHARINDEX('' '',RTRIM(LTRIM(FullName)),0) > 0'
	
	--temp table for data generated by dynamic query--
	CREATE TABLE #wow_temp
	(	
		Username nvarchar(256) not null
		,[Password] nvarchar(256) not null
		,FirstName nvarchar(256) null
		,LastName nvarchar(256) null
		,Email nvarchar(256) null
		,[Status] smallint null
		,Phone nvarchar(30) null
		,Create_date datetime null
		,Is_System_User bit not null
		,Default_System_Id int null
	)
	
	INSERT INTO #wow_temp EXEC(@SQL)	
	
		--insert not existing user--
	INSERT INTO [Dart].[dbo].[Users] (UserName, [Password], FirstName, LastName, Email, [Status], Phone, Create_Date, Is_System_User, Default_System_Id)
	SELECT *
	FROM #wow_temp
	WHERE UserName COLLATE SQL_Latin1_General_CP1_CI_AS not in (SELECT UserName FROM [Dart].[dbo].[Users] WHERE UserName like '%WOW%')
		
		--update existing user--	
	UPDATE [Dart].[dbo].[Users]
	SET [Password] = t.[Password]
		,FirstName = t.FirstName
		,LastName = t.LastName
		,Email = t.Email
		,[Status] = t.[Status]
		,Phone = t.Phone
	FROM [Dart].[dbo].[Users] u INNER JOIN #wow_temp t
	ON u.UserName COLLATE SQL_Latin1_General_CP1_CI_AS = t.Username
	WHERE u.[Password] COLLATE SQL_Latin1_General_CP1_CI_AS <> t.[Password]
	OR u.FirstName COLLATE SQL_Latin1_General_CP1_CI_AS <> t.FirstName
	OR u.LastName COLLATE SQL_Latin1_General_CP1_CI_AS <> t.LastName
	OR u.Email COLLATE SQL_Latin1_General_CP1_CI_AS <> t.Email
	OR u.[Status] <> t.[Status]
	OR u.Phone COLLATE SQL_Latin1_General_CP1_CI_AS <> t.Phone
	
	--ADD WOW USERS TO REPORT USER TABLE-- 
	SELECT @WOW_Internal_Group_Id = External_GroupId
	FROM [Dart].[dbo].[External_Groups]
	WHERE Name like '%WOW Internal%'
	
	SELECT @WOW_External_Group_Id = External_GroupId
	FROM [Dart].[dbo].[External_Groups]
	WHERE Name like '%WOW External%'
	
	INSERT INTO [Dart].[dbo].[ReportUsers] (UserId, Is_External_User, External_GroupId)
	SELECT u.UserId, 1, External_GroupId = case when (u.Email like '%@aswigsolutions.com%'
												      or u.Email like '%@employersmutual.com.au%')
													then @WOW_Internal_Group_Id
												when u.Email like '%@woolworths.com.au%'
													then @WOW_External_Group_Id
											end
	FROM [Dart].[dbo].[Users] u  
	LEFT JOIN [Dart].[dbo].[ReportUsers] ru 
	ON ru.UserId = u.UserId
	WHERE ru.UserId is null
	AND u.UserName like '%WOW\%'
	
	--ADD WOW EXTERNAL GROUP TO DASHBOARD EXTERNAL GROUP--		
	--check existing before inserting--
	INSERT INTO [Dart].[dbo].[DashboardExternal_Groups] (DashboardId, DashboardLevelId, External_GroupId, Create_Date)
	SELECT dashboard.DashboardId, dashboard_Level.DashboardLevelId, ext_group.External_GroupId, getdate()
	FROM [Dart].[dbo].[Dashboards] dashboard 
	CROSS JOIN [Dart].[dbo].[Dashboard_Levels] dashboard_Level
	CROSS JOIN [Dart].[dbo].[External_Groups] ext_group 
	LEFT JOIN [Dart].[dbo].[DashboardExternal_Groups] dexg
	on dashboard.DashboardId = dexg.DashboardId
	AND dashboard_Level.DashboardLevelId = dexg.DashboardLevelId
	AND ext_group. External_GroupId = dexg.External_GroupId
	WHERE dexg.DashboardId is null
	AND dashboard.Name like '%WOW%'
	AND dashboard_Level.Sort <> 1
	AND ext_group.Name like	'%WOW%'
	
	IF OBJECT_ID('tempdb..#wow_temp') IS NOT NULL DROP TABLE #wow_temp
	
END
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON

