//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EM_Report.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dashboard_Traffic_Light_RuleDO
    {
        public int Id { get; set; }
        public int SystemId { get; set; }
        public string DashboardType { get; set; }
        public string Type { get; set; }
        public string Value { get; set; }
        public string Sub_Value { get; set; }
        public Nullable<int> Measure { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<double> FromValue { get; set; }
        public Nullable<double> ToValue { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<int> Owner { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
