//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EM_Report.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class External_GroupDO
    {
        public External_GroupDO()
        {
            this.Report_External_Access = new HashSet<Report_External_AccessDO>();
            this.ReportUsers = new HashSet<ReportUserDO>();
        }
    
        public int External_GroupId { get; set; }
        public string Name { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<int> Owner { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string Description { get; set; }
        public Nullable<int> SystemId { get; set; }
    
        public virtual ICollection<Report_External_AccessDO> Report_External_Access { get; set; }
        public virtual ICollection<ReportUserDO> ReportUsers { get; set; }
    }
}
