//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EM_Report.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_PermissionDO
    {
        public System_PermissionDO()
        {
            this.System_Role_Permissions = new HashSet<System_Role_PermissionDO>();
        }
    
        public int System_PermissionId { get; set; }
        public string Name { get; set; }
        public Nullable<short> Status { get; set; }
    
        public virtual ICollection<System_Role_PermissionDO> System_Role_Permissions { get; set; }
    }
}
