//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EM_Report.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Role_PermissionDO
    {
        public int System_RoleId { get; set; }
        public int PermissionId { get; set; }
        public int System_PermissionId { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<int> Owner { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual PermissionDO Permission { get; set; }
        public virtual System_PermissionDO System_Permissions { get; set; }
        public virtual System_RoleDO System_Roles { get; set; }
    }
}
