//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EM_Report.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisation_LevelDO
    {
        public Organisation_LevelDO()
        {
            this.Dashboard_OrganisationRole_Levels = new HashSet<Dashboard_OrganisationRole_LevelDO>();
            this.Organisation_Roles = new HashSet<Organisation_RoleDO>();
            this.Report_Organisation_Levels = new HashSet<Report_Organisation_LevelDO>();
        }
    
        public int LevelId { get; set; }
        public int SystemId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Sort { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<int> Owner { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<short> Status { get; set; }
    
        public virtual ICollection<Dashboard_OrganisationRole_LevelDO> Dashboard_OrganisationRole_Levels { get; set; }
        public virtual ICollection<Organisation_RoleDO> Organisation_Roles { get; set; }
        public virtual ICollection<Report_Organisation_LevelDO> Report_Organisation_Levels { get; set; }
    }
}
