//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EM_Report.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportUserDO
    {
        public int UserId { get; set; }
        public Nullable<bool> Is_External_User { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<int> Organisation_RoleId { get; set; }
        public Nullable<int> External_GroupId { get; set; }
        public int Id { get; set; }
    
        public virtual External_GroupDO External_GroupDO { get; set; }
        public virtual Organisation_RoleDO Organisation_RoleDO { get; set; }
        public virtual UserDO UserDO { get; set; }
        public virtual TeamDO TeamDO { get; set; }
    }
}
