//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EM_Report.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_RoleDO
    {
        public System_RoleDO()
        {
            this.System_Role_Permissions = new HashSet<System_Role_PermissionDO>();
            this.SystemUserDOs = new HashSet<SystemUserDO>();
        }
    
        public int System_RoleId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<System_Role_PermissionDO> System_Role_Permissions { get; set; }
        public virtual ICollection<SystemUserDO> SystemUserDOs { get; set; }
    }
}
