/****** Object:  StoredProcedure [dbo].[usp_AmountDueReportForDebtActionsByFundYear]    Script Date: 04/12/2012 23:27:49 ******/
IF  EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N'[dbo].[usp_AmountDueReportForDebtActionsByFundYear]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
DROP PROCEDURE [dbo].[usp_AmountDueReportForDebtActionsByFundYear]
GO

/****** Object:  StoredProcedure [dbo].[usp_AmountDueReportForDebtActionsByFundYear]    Script Date: 04/12/2012 23:27:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[usp_AmountDueReportForDebtActionsByFundYear] 
	@Reporting_Date datetime,
	@Debt_Actions varchar(20),
	@Is_Broker bit,
	@Policies varchar(8000),
	@Broker varchar(8)
AS
BEGIN
	SET NOCOUNT ON;
	
	CREATE TABLE #DEBT_ACTION
	(
		Debt_Action_Code tinyint
	)
	
	CREATE TABLE #POLICY
	(
		value varchar(30)
	)
	
	CREATE TABLE #TEMP
	(   
		DEBT_ACTION_CODE tinyint,
		Fund_Year smallint,
		Amount money,
		Type varchar(20)
	)
	INSERT INTO #POLICY
	SELECT * FROM dbo.udf_Split(@Policies, ',')
	
	INSERT INTO #DEBT_ACTION
	SELECT * FROM dbo.udf_Split(@Debt_Actions, ',')
	
	IF ((SELECT COUNT(*) FROM #DEBT_ACTION) = 2) BEGIN
		RAISERROR ('Choose 1 or all 3 Debt Action!', 10, 1)
		RETURN
	END
	
	INSERT INTO #TEMP
	SELECT
		PD.DEBT_ACTION_CODE,
		Fund_Year = DT.FUND_YEAR,
		Amount = SUM(DT.UNALLOC),
		Type = '<= 30 Days'
	FROM DTRANS DT JOIN PREMIUM_DETAIL PD ON PD.POLICY_NO = DT.POLICY_NO AND PD.RENEWAL_NO = DT.RENEWAL_NO
		JOIN POLICY_TERM_DETAIL PTD ON PTD.POLICY_NO = PD.POLICY_NO
	WHERE DATEDIFF(DAY, DT.DUE_DATE, @Reporting_Date) <= 30
		AND DT.CANCELLED = 0
		AND PD.DEBT_ACTION_CODE IN (SELECT * FROM #DEBT_ACTION)
		AND ((@Is_Broker = 0 AND PTD.POLICY_NO IN (SELECT * FROM dbo.udf_Split(@Policies, ',')))
			OR (@Is_Broker = 1 AND PTD.BROKER_NO = @Broker))
		AND DT.FUND_YEAR IS NOT NULL
	GROUP BY Fund_Year, PD.DEBT_ACTION_CODE
	UNION
	SELECT
		PD.DEBT_ACTION_CODE,
		Fund_Year = DT.FUND_YEAR,
		Amount = SUM(DT.UNALLOC),
		Type = '31 - 60 Days'
	FROM DTRANS DT JOIN PREMIUM_DETAIL PD ON PD.POLICY_NO = DT.POLICY_NO AND PD.RENEWAL_NO = DT.RENEWAL_NO
		JOIN POLICY_TERM_DETAIL PTD ON PTD.POLICY_NO = PD.POLICY_NO
	WHERE DATEDIFF(DAY, DT.DUE_DATE, @Reporting_Date) BETWEEN 31 AND 60
		AND DT.CANCELLED = 0
		AND PD.DEBT_ACTION_CODE IN (SELECT * FROM #DEBT_ACTION)
		AND ((@Is_Broker = 0 AND PTD.POLICY_NO IN (SELECT * FROM dbo.udf_Split(@Policies, ',')))
			OR (@Is_Broker = 1 AND PTD.BROKER_NO = @Broker))
		AND DT.FUND_YEAR IS NOT NULL
	GROUP BY Fund_Year, PD.DEBT_ACTION_CODE
	UNION
	SELECT
		PD.DEBT_ACTION_CODE,
		Fund_Year = DT.FUND_YEAR,
		Amount = SUM(DT.UNALLOC),
		Type = '61 - 90 Days'
	FROM DTRANS DT JOIN PREMIUM_DETAIL PD ON PD.POLICY_NO = DT.POLICY_NO AND PD.RENEWAL_NO = DT.RENEWAL_NO
		JOIN POLICY_TERM_DETAIL PTD ON PTD.POLICY_NO = PD.POLICY_NO
	WHERE DATEDIFF(DAY, DT.DUE_DATE, @Reporting_Date) BETWEEN 61 AND 90
		AND DT.CANCELLED = 0
		AND PD.DEBT_ACTION_CODE IN (SELECT * FROM #DEBT_ACTION)
		AND ((@Is_Broker = 0 AND PTD.POLICY_NO IN (SELECT * FROM dbo.udf_Split(@Policies, ',')))
			OR (@Is_Broker = 1 AND PTD.BROKER_NO = @Broker))
		AND DT.FUND_YEAR IS NOT NULL
	GROUP BY Fund_Year, PD.DEBT_ACTION_CODE
	UNION
	SELECT
		PD.DEBT_ACTION_CODE,
		Fund_Year = DT.FUND_YEAR,
		Amount = SUM(DT.UNALLOC),
		Type = '91 - 120 Days'
	FROM DTRANS DT JOIN PREMIUM_DETAIL PD ON PD.POLICY_NO = DT.POLICY_NO AND PD.RENEWAL_NO = DT.RENEWAL_NO
		JOIN POLICY_TERM_DETAIL PTD ON PTD.POLICY_NO = PD.POLICY_NO
	WHERE DATEDIFF(DAY, DT.DUE_DATE, @Reporting_Date) BETWEEN 91 AND 120
		AND DT.CANCELLED = 0
		AND PD.DEBT_ACTION_CODE IN (SELECT * FROM #DEBT_ACTION)
		AND ((@Is_Broker = 0 AND PTD.POLICY_NO IN (SELECT * FROM dbo.udf_Split(@Policies, ',')))
			OR (@Is_Broker = 1 AND PTD.BROKER_NO = @Broker))
		AND DT.FUND_YEAR IS NOT NULL
	GROUP BY Fund_Year, PD.DEBT_ACTION_CODE
	UNION
	SELECT PD.DEBT_ACTION_CODE,
		Fund_Year = DT.FUND_YEAR,
		Amount = sum(DT.UNALLOC),
		Type = '121 - 180 Days'
	FROM DTRANS DT JOIN PREMIUM_DETAIL PD ON PD.POLICY_NO = DT.POLICY_NO AND PD.RENEWAL_NO = DT.RENEWAL_NO
		JOIN POLICY_TERM_DETAIL PTD ON PTD.POLICY_NO = PD.POLICY_NO
	WHERE DATEDIFF(DAY, DT.DUE_DATE, @Reporting_Date) BETWEEN 121 AND 180		
		AND DT.CANCELLED = 0
		AND PD.DEBT_ACTION_CODE IN (SELECT * FROM #DEBT_ACTION)
		AND ((@Is_Broker = 0 AND PTD.POLICY_NO IN (SELECT * FROM dbo.udf_Split(@Policies, ',')))
				OR (@Is_Broker = 1 AND PTD.BROKER_NO = @Broker))
		AND DT.FUND_YEAR IS NOT NULL
	GROUP BY Fund_Year, PD.DEBT_ACTION_CODE
	UNION
	SELECT PD.DEBT_ACTION_CODE,
		Fund_Year = DT.FUND_YEAR,
		Amount = sum(DT.UNALLOC),
		Type = '> 180 Days'
	FROM DTRANS DT JOIN PREMIUM_DETAIL PD ON PD.POLICY_NO = DT.POLICY_NO AND PD.RENEWAL_NO = DT.RENEWAL_NO
		JOIN POLICY_TERM_DETAIL PTD ON PTD.POLICY_NO = PD.POLICY_NO
	WHERE DATEDIFF(DAY, DT.DUE_DATE, @Reporting_Date) > 180		
		AND DT.CANCELLED = 0
		AND PD.DEBT_ACTION_CODE IN (SELECT * FROM #DEBT_ACTION)
		AND ((@Is_Broker = 0 AND PTD.POLICY_NO IN (SELECT * FROM dbo.udf_Split(@Policies, ',')))
				OR (@Is_Broker = 1 AND PTD.BROKER_NO = @Broker))
		AND DT.FUND_YEAR IS NOT NULL
	GROUP BY Fund_Year, PD.DEBT_ACTION_CODE
	
	SELECT *
	FROM #TEMP
	
	
	DROP TABLE #TEMP
END

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO
 
GRANT  EXECUTE  ON [dbo].[usp_AmountDueReportForDebtActionsByFundYear]  TO [EMICS]
GO
 
GRANT  EXECUTE  ON [dbo].[usp_AmountDueReportForDebtActionsByFundYear]  TO [emius]
GO

-- exec [usp_AmountDueReportForDebtActionsByFundYear] '20120430', '66,67,70', 0, '10035181,10037181,10066181,10084181,10112181,10248181,1NFE000395GWC154,1NFE004287WC1G54,1NFE009306GWC154,22WOR0190516122, 98578016,WC454774157, WC459325157', '' 

